[server]
enableStaticServing = true

[theme]
base="dark"
primaryColor="#0E76A8"               # You can customize this
backgroundColor="#0E1117"            # Dark background
secondaryBackgroundColor="#262730"  # Darker sidebar
textColor="#FAFAFA"                  # Light text


[client]
toolbarMode = "minimal"